version: '3'

services:
  serving:
    build:
      context: ./  
      dockerfile: ./Dockerfile.serving
    image: ift6758/serving:latest
    ports:
      - 5000:5000 
    environment:
      - WANDB_API_KEY=${WANDB_API_KEY}
      - PYTHONUNBUFFERED=1

  streamlit:
    build:
      context: ./ 
      dockerfile: ./Dockerfile.streamlit
    image: ift6758/streamlit:latest
    ports:
      - 8501:8501
    environment:
      - STREAMLIT_PORT=8501
      - STREAMLIT_IP=0.0.0.0
